pipeline {
    agent any
    environment {
        Defaultworkspace = '/project1/java-docker-jenkins-app'
        //SONARQUBE_URL = 'http://your-sonarqube-server:9000'
        //SONARQUBE_AUTH_TOKEN = credentials('sonarqube-auth-token')
    }

    stages {
        stage('Code Checkout') {
            steps {
               checkout scm
               sh 'echo "Code checked out successfully!"'
               sh'cd ${Defaultworkspace} && ls -la' 
            }
        }
        stage('Maven Build') {
            steps {
        // 'maven-3.9.15' should match the name you gave it in Global Tool Configuration
            withMaven(maven: 'maven-3.9.15') {
            sh "mvn clean package"
        }
    }
        }
        stage('SonarQube Testing') {
            steps {
                sh 'mvn sonar:sonar'
            }
        }
        stage('Docker Build') {
            steps {
                sh 'docker build -t your-image-name:latest .'
            }
        }
        stage('Docker ECR Push') {
            steps {
                script {
                    def awsAccountId = 'your-aws-account-id'
                    def region = 'your-region'
                    def repositoryName = 'your-repo-name'
                    def imageTag = 'latest'

                    sh "aws ecr get-login-password --region ${region} | docker login --username AWS --password-stdin ${awsAccountId}.dkr.ecr.${region}.amazonaws.com"
                    sh "docker tag your-image-name:${imageTag} ${awsAccountId}.dkr.ecr.${region}.amazonaws.com/${repositoryName}:${imageTag}"
                    sh "docker push ${awsAccountId}.dkr.ecr.${region}.amazonaws.com/${repositoryName}:${imageTag}"
                }
            }
        }
        stage('Deploy Container') {
            steps {
                sh 'docker run -d -p 9090:8080 your-image-name:latest'
            }
        }
    }
}