projectKey=java-docker-jenkins-app
projectName=Java Docker Jenkins Application
projectVersion=1.0.0
sources=src/main/java
language=java
sonar.sourceEncoding=UTF-8
sonar.java.binaries=target/classes
sonar.exclusions=**/test/**, **/src/test/**